"""adding scraping status and lot_description

Revision ID: 3f260d0c6b3e
Revises: 037d4808e987
Create Date: 2025-04-03 21:16:59.000599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f260d0c6b3e'
down_revision: Union[str, None] = '037d4808e987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('status', sa.String(), nullable=True))
    op.add_column('lots', sa.Column('lot_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'lot_description')
    op.drop_column('lots', 'status')
    # ### end Alembic commands ###
