"""adding lot_number to lots

Revision ID: 4501a8120b05
Revises: 
Create Date: 2025-04-03 20:30:01.114386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4501a8120b05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lots_id', table_name='lots')
    op.drop_table('lots')
    op.drop_index('ix_websites_id', table_name='websites')
    op.drop_index('ix_websites_name', table_name='websites')
    op.drop_table('websites')
    op.drop_index('ix_auctions_id', table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('auction_link', sa.VARCHAR(), nullable=True),
    sa.Column('auction_title', sa.VARCHAR(), nullable=True),
    sa.Column('n_lots', sa.INTEGER(), nullable=True),
    sa.Column('last_scraped', sa.DATETIME(), nullable=True),
    sa.Column('website_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_link')
    )
    op.create_index('ix_auctions_id', 'auctions', ['id'], unique=False)
    op.create_table('websites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_scraped', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index('ix_websites_name', 'websites', ['name'], unique=1)
    op.create_index('ix_websites_id', 'websites', ['id'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('auction_id', sa.INTEGER(), nullable=True),
    sa.Column('lot_link', sa.VARCHAR(), nullable=True),
    sa.Column('lot_title', sa.VARCHAR(), nullable=True),
    sa.Column('lot_slug', sa.VARCHAR(), nullable=True),
    sa.Column('lot_uid', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('image_links', sa.VARCHAR(), nullable=True),
    sa.Column('is_scraped', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('scraped_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_link')
    )
    op.create_index('ix_lots_id', 'lots', ['id'], unique=False)
    # ### end Alembic commands ###
