"""set default value pending for status

Revision ID: 8b016ff56a2a
Revises: 72c91e801a2b
Create Date: 2025-04-03 22:56:57.991271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b016ff56a2a'
down_revision: Union[str, None] = '72c91e801a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lots_id'), 'lots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lots_id'), table_name='lots')
    # ### end Alembic commands ###
